sudo: required
services:
  - docker

before_install:
  - docker build -t mateusz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mateusz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-eu-west-1-176901363719"
  bucket_path: "docker-react-2"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
